---
# tasks file for emacs
#
# see: https://macowners.club/posts/using-xwidgets-on-macos/
# see: https://github.com/d12frosted/homebrew-emacs-plus#emacs-29-and-emacs-30
- name: Install emacs-plus
  block:
    - name: Tap d12frosted/emacs-plus (homebrew)
      homebrew_tap:
        name: d12frosted/emacs-plus
        state: present

    - name: "Install emacs-plus@{{ emacs_plus_version }} (homebrew)"
      community.general.homebrew:
        name: "emacs-plus@{{ emacs_plus_version }}"
        state: present
        install_options: with-xwidgets,with-imagemagick
        # install_options: with-xwidgets,with-imagemagick,with-native-comp

    # - name: Get installed location (homebrew)
    #   shell:
    #     cmd: brew list "emacs-plus@{{ emacs_plus_version }}" | grep Emacs.app | sed -e 's/Emacs.app.*$/Emacs.app/g' | head -n 1
    #   register: emacs_homebrew_installed_path

    # - name: Install Emacs.app (homebrew)
    #   copy:
    #     src: "{{ emacs_homebrew_installed_path.stdout }}"
    #     dest: /Applications
    #     mode: preserve
    #     force: no

  tags: install
  when: ansible_pkg_mgr == 'homebrew'

- name: Add Emacs PPA for Ubuntu 22.04
  apt_repository: repo='ppa:ubuntuhandbook1/emacs' state=present
  become: true
  tags: install
  when: ansible_pkg_mgr == 'apt' and ansible_distribution|lower == 'ubuntu' and ansible_distribution_major_version == 22
    
- name: Install Emacs (apt)
  apt:
    name: ["emacs"]
    state: present
    update_cache: true
  become: true

  tags: install
  when: ansible_pkg_mgr == 'apt'

- name: Legacy Emacs 24-bit support
  when: emacs.legacy_24bit | default(False)
  include_tasks: legacy_24bit.yml

- name: Create .emacs.d directory
  file:
    path: "{{ ansible_env.HOME }}/.emacs.d"
    state: directory
  tags: configure

- name: "Write emacs configuration to {{ emacs_config }}"
  template:
    src: emacs.j2
    dest: "{{ emacs_config }}"
    backup: yes
  when: emacs_create_initel == True
  tags: configure

- name: "Download configuration files from remote urls"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.HOME }}/.emacs.d/{{ item.dest }}"
    url_username: "{{ item.url_username | default(omit) }}"
    url_password: "{{ item.url_password | default('') }}"
    force_basic_auth: "{{ item.force_basic_auth | default('no') }}"
  loop: "{{ emacs.copy_files }}"
  when: emacs.copy_files is defined
  tags: configure
