---
# tasks file for emacs
- name: Install emacs-mac from Railwaycat's repo
  block:
    - name: Tap railwaycat's emacs-mac (homebrew)
      homebrew_tap:
        name: railwaycat/emacsmacport
        state: present

    - name: Install emacs-mac from bottle (homebrew)
      community.general.homebrew_cask:
        name: emacs-mac
        state: present

  tags: install 
  when: ansible_pkg_mgr == 'homebrew'

- name: Install emacs26 (apt)
  block:
    - name: Add Emacs 26 apt repository for Ubuntu
      apt_repository:
        repo: ppa:kelleyk/emacs
        state: present
      become: yes

    - name: Install Emacs (apt)
      apt:
        name: ['emacs26-nox']
        state: present
        update_cache: true
      become: yes

  tags: install
  when: ansible_pkg_mgr == 'apt'

# for Emacs 24-bit color support: https://stackoverflow.com/a/50577683/57626
- name: Check for 24-bit termcap definition
  shell:
    cmd: if [ -d ~/.terminfo ]; then find ~/.terminfo -type f -name xterm-24bits; fi
  register: find_xterm24bits
  ignore_errors: true
  when: ansible_os_family|lower == 'debian' or ansible_os_family|lower == 'darwin'
  tags: configure

- name: Create temporary file for 24-bit emacs support
  tempfile:
    state: file
    suffix: temp
  register: tempfile_1
  when: find_xterm24bits is defined and find_xterm24bits.stdout == ""
  tags: configure

- name: Set up Emacs for 24-bit support
  copy:
    src: emacs-24-bit
    dest: "{{ tempfile_1.path }}"
  when: find_xterm24bits is defined and find_xterm24bits.stdout == ""
  tags: configure

- name: Compile Emacs 24-bit terminal
  shell: "tic -x -o ~/.terminfo {{ tempfile_1.path }}"
  when: find_xterm24bits is defined and find_xterm24bits.stdout == ""
  tags: configure

- name: Install 24-bit color zsh alias
  template:
    src: emacs.zsh.j2
    dest: "{{ ansible_env.HOME }}/.zshrc.d/emacs.zsh"
  when: emacs.install_zsh is defined and emacs.install_zsh == True
  tags: configure

- name: Install 24-bit color bash alias
  template:
    src: emacs.sh.j2
    dest: "{{ ansible_env.HOME }}/.bashrc.d/emacs.sh"
  when: emacs.install_bash is defined and emacs.install_bash == True
  tags: configure

- name: Install 24-bit color fish alias
  template:
    src: emacs.fish.j2
    dest: "{{ ansible_env.HOME }}/.config/fish/fish.d/emacs.fish"
  when: emacs.install_fish is defined and emacs.install_fish == True
  tags: configure

- name: Create .emacs.d directory
  file:
    path: "{{ ansible_env.HOME }}/.emacs.d"
    state: directory
  tags: configure

- name: "Write emacs configuration to {{ emacs_config }}"
  template:
    src: emacs.j2
    dest: "{{ emacs_config }}"
    backup: yes
  when: emacs_create_initel == True
  tags: configure

- name: "Download configuration files from remote urls"
  get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.HOME }}/.emacs.d/{{ item.dest }}"
  tags: configure
  loop: "{{ emacs.copy_files }}"
  when: emacs.copy_files is defined
